VL-122_Typescript-errors-fix_Vitalii-Dudnik
vuelessjs/vueless pull request #275
Opened 2024-11-28 12:26 UTC by KinduD21

Fix TS errors in different component groups

https://ilevel.atlassian.net/jira/software/c/projects/VL/boards/11?selectedIssue=VL-122

2024-11-28 14:55 UTC, itsJohnnyGrid commented on src/ui.navigation-pagination/UPagination.vue
> +  return props.disabled || currentPage.value == null || currentPage.value <= 1;
== ??? why ?

2024-11-28 14:55 UTC, itsJohnnyGrid commented on src/ui.navigation-pagination/UPagination.vue
> +  return props.disabled || currentPage.value == null || currentPage.value >= totalPages.value;
same

2024-11-28 14:55 UTC, itsJohnnyGrid commented on src/ui.navigation-pagination/UPagination.vue
> +  currentPage.value = currentPage.value == null ? 1 : Math.max(currentPage.value - 1, 1);
same

2024-11-28 14:55 UTC, itsJohnnyGrid commented on src/ui.navigation-pagination/UPagination.vue
> +    currentPage.value == null
same

2024-11-28 14:55 UTC, itsJohnnyGrid commented on src/ui.text-files/UFiles.vue
> +function onRemoveFile(fileId: number) {
may be string also

2024-11-28 14:55 UTC, itsJohnnyGrid commented on src/ui.text-notify/UNotify.vue
> +    const xPos = props.xPosition as "left" | "right";
`props.xPosition` is typed? this looks weird to me

2024-12-02 09:50 UTC, Explicit12 requested changes

2024-12-02 09:50 UTC, Explicit12 commented on src/ui.container-page/UPage.vue
> +  const body = document.querySelector("body");
There is no need to use `querySelector` here. Just use `document.body`.

2024-12-02 09:50 UTC, Explicit12 commented on src/ui.text-files/types.ts
> +  fileList?: UFileItem[];
It should accept array of [File objects](https://developer.mozilla.org/en-US/docs/Web/API/File)

2024-12-02 09:50 UTC, Explicit12 commented on src/ui.text-files/UFiles.vue
> +          :image-url="file?.imageUrl"
Replace UFileItem with File and you probably don't need those optional chaining operators

2024-12-02 10:40 UTC, Explicit12 approved these changes

2024-12-02 11:05 UTC, itsJohnnyGrid commented on src/ui.text-files/UFiles.vue
> +    if (!(file instanceof File)) {
may be Blob also I guess.

2024-12-02 11:06 UTC, itsJohnnyGrid commented on src/ui.text-files/types.ts
> +  fileList?: File[] | FileList;
Blob ?

2024-12-02 14:26 UTC, itsJohnnyGrid commented on src/ui.text-files/UFiles.vue
> +        label: file instanceof File ? file.name : file instanceof Blob ? file.type : "",
Are you sure? need to discuss.

2024-12-03 09:44 UTC, itsJohnnyGrid commented on src/ui.text-files/UFiles.vue
>          return null;
need to discuss

2024-12-03 10:43 UTC, itsJohnnyGrid approved these changes

2024-12-03 10:45 UTC, merged